import { CONFIG } from "./config.js";
import { loadJson, loadCsv } from "./dataLoader.js";
import { qs, formatDate, turbineRecommendation, scoreBadge } from "./utils.js";
import { getState, setState } from "./state.js";
import { getUserLocation, nearestStation } from "./geo.js";
import { setActiveNav } from "./navActive.js";

let stations = [];
let summary = [];

function findSummary(name) { return summary.find(r => r.station === name); }

function fillStations(selectEl) {
  selectEl.innerHTML = stations.map(s => `<option value="${s.name}">${s.name}</option>`).join("");
}

function fillPreview(name, modeText) {
  const s = stations.find(x => x.name === name);
  const row = findSummary(name);
  if (!s || !row) return;

  const f1 = Number(row.forecast_1m_ms);
  const f3 = Number(row.forecast_3m_ms);
  const f6 = Number(row.forecast_6m_ms);
  const b = scoreBadge(f1);

  document.getElementById("stationName").textContent = name;
  document.getElementById("modeText").textContent = modeText;
  document.getElementById("coords").textContent = `${s.lat.toFixed(3)}, ${s.lon.toFixed(3)}`;
  document.getElementById("dir").textContent = s.direction_hint || "—";

  const badge = document.getElementById("badge");
  badge.textContent = b.label;
  badge.className = `badge ${b.className}`;

  document.getElementById("f1").textContent = `${f1.toFixed(3)} m/s (${formatDate(row.date_1m)})`;
  document.getElementById("f3").textContent = `${f3.toFixed(3)} m/s (${formatDate(row.date_3m)})`;
  document.getElementById("f6").textContent = `${f6.toFixed(3)} m/s (${formatDate(row.date_6m)})`;

  document.getElementById("rec").textContent = turbineRecommendation(f1);
}

async function useMyLocation() {
  document.getElementById("locStatus").textContent = "Getting your location…";
  try {
    const loc = await getUserLocation();
    setState({ userLocation: loc });

    const near = nearestStation(loc.lat, loc.lon, stations);
    const name = near.station.name;
    setState({ selectedStation:name, selectionMode:"nearest", nearestDistanceKm: near.distanceKm });

    document.getElementById("stationSelect").value = name;
    document.getElementById("locStatus").textContent = `Nearest station: ${name} (~${near.distanceKm.toFixed(1)} km).`;
    fillPreview(name, `Nearest station (~${near.distanceKm.toFixed(1)} km)`);
  } catch {
    document.getElementById("locStatus").textContent = "Location failed or permission denied.";
  }
}

function downloadPdf() {
  const st = getState();
  const name = document.getElementById("stationSelect").value;
  const horizon = Number(document.getElementById("horizon").value);

  const s = stations.find(x => x.name === name);
  const row = findSummary(name);
  if (!s || !row) return;

  const modeLine =
    st.selectionMode === "nearest" && st.nearestDistanceKm
      ? `Nearest-station mode (~${Number(st.nearestDistanceKm).toFixed(1)} km)`
      : "Station selected";

  const fMap = {
    1: { v:Number(row.forecast_1m_ms), d:row.date_1m },
    3: { v:Number(row.forecast_3m_ms), d:row.date_3m },
    6: { v:Number(row.forecast_6m_ms), d:row.date_6m },
  };

  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  doc.setFont("helvetica","bold");
  doc.setFontSize(16);
  doc.text("WindCast FYP — Wind Forecast & Recommendation Report", 14, 18);

  doc.setFont("helvetica","normal");
  doc.setFontSize(11);
  doc.text(`Station used: ${name}`, 14, 32);
  doc.text(`Mode: ${modeLine}`, 14, 39);
  doc.text(`Coordinates: ${s.lat.toFixed(3)}, ${s.lon.toFixed(3)}`, 14, 46);
  doc.text(`Prevailing direction (hint): ${s.direction_hint || "—"}`, 14, 53);

  doc.setFont("helvetica","bold");
  doc.text("Forecast snapshot (from your CSV outputs)", 14, 66);
  doc.setFont("helvetica","normal");
  doc.text(`Lead 1: ${Number(row.forecast_1m_ms).toFixed(3)} m/s on ${row.date_1m}`, 14, 74);
  doc.text(`Lead 3: ${Number(row.forecast_3m_ms).toFixed(3)} m/s on ${row.date_3m}`, 14, 81);
  doc.text(`Lead 6: ${Number(row.forecast_6m_ms).toFixed(3)} m/s on ${row.date_6m}`, 14, 88);

  doc.setFont("helvetica","bold");
  doc.text(`Selected horizon: Lead ${horizon}`, 14, 102);
  doc.setFont("helvetica","normal");
  doc.text(`Forecast at this horizon: ${fMap[horizon].v.toFixed(3)} m/s (${fMap[horizon].d})`, 14, 110);

  doc.setFont("helvetica","bold");
  doc.text("Recommendation (rule-based demo; replace later with your final logic)", 14, 124);
  doc.setFont("helvetica","normal");
  doc.text(doc.splitTextToSize(`Recommendation: ${turbineRecommendation(Number(row.forecast_1m_ms))}`, 180), 14, 132);

  doc.setFontSize(9);
  doc.text("Generated by WindCast static web demo (HTML/CSS/JS).", 14, 282);

  doc.save(`WindCast_Report_${name.replace(/\s+/g,"_")}_H${horizon}.pdf`);
}

async function init() {
  setActiveNav("report");
  stations = await loadJson(CONFIG.paths.stationsJson);
  summary  = await loadCsv(CONFIG.paths.forecastsSummaryCsv);

  fillStations(document.getElementById("stationSelect"));

  const st = getState();
  const initial = qs("station") || st.selectedStation || stations[0].name;
  document.getElementById("stationSelect").value = initial;

  const modeText =
    st.selectionMode === "nearest" && st.nearestDistanceKm
      ? `Nearest station (~${Number(st.nearestDistanceKm).toFixed(1)} km)`
      : "Station selected";

  fillPreview(initial, modeText);

  document.getElementById("stationSelect").addEventListener("change", (e) => {
    setState({ selectedStation:e.target.value, selectionMode:"station" });
    fillPreview(e.target.value, "Station selected");
  });

  document.getElementById("useLocation").addEventListener("click", useMyLocation);
  document.getElementById("downloadPdf").addEventListener("click", downloadPdf);
}

document.addEventListener("DOMContentLoaded", init);